# Generated by Django 4.2.8 on 2024-01-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=15, verbose_name="Enter ur name : "),
                ),
                ("last_name", models.CharField(max_length=15)),
                ("phone", models.BigIntegerField()),
                ("email", models.EmailField(max_length=30)),
            ],
        ),
    ]
