# Generated by Django 4.2.8 on 2024-01-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=15, verbose_name="Enter ur name : "),
                ),
                ("last_name", models.CharField(max_length=15)),
                ("dob", models.DateField()),
                ("age", models.IntegerField()),
                ("phone", models.BigIntegerField()),
                ("email", models.EmailField(max_length=30)),
                (
                    "deprt",
                    models.CharField(
                        choices=[
                            ("HR", "Humen Resourse"),
                            ("CS", "Computer science"),
                            ("EC", "Electronics and Commun"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_emp",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=15)),
                ("last_name", models.CharField(max_length=15)),
                ("dob", models.DateField()),
                ("age", models.IntegerField()),
                ("phone", models.BigIntegerField()),
                ("email", models.EmailField(max_length=30)),
            ],
            options={
                "db_table": "tblStud",
            },
        ),
    ]
